export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const isREGISTER = 'isREGISTER'
export const isGOOGLELOGIN = 'isGOOGLELOGIN'
export const CATEGORY = 'CATEGORY'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'
